const ADD_USER = "ADD_USER";
const LOG_USERIN = "LOG_USERIN";
const DELETE_PLACE = "DELETE_PLACE";
const MODIFY_PLACE = "MODIFY_PLACE";
const ADD_PLACE = "ADD_PLACE";
const LOG_USEROUT = "LOG_USEROUT";
const LOAD_PLACES = "LOAD_PLACES";
const LOAD_USERS = "LOAD_USERS";
const ADD_ALERT = "ADD_ALERT";
const REMOVE_ALERT = "REMOVE_ALERT";

module.exports = {
  LOAD_USERS,
  REMOVE_ALERT,
  ADD_ALERT,
  LOAD_PLACES,
  ADD_PLACE,
  ADD_USER,
  LOG_USERIN,
  LOG_USEROUT,
  DELETE_PLACE,
  MODIFY_PLACE,
};
